### ISSUE TITLE
live preview is not working

### ISSUE THREAD

**Issue by lindamacdonald** [Contentrain/the-roads#2]
Hey there gang :) just wanted to let you know that the live preview for the Svelte demo isnt working, Its showing:
Not Found - Request ID: 01GJA6YDX0221HNK16Z6YV19NP

**Comment by ABB65** [comment]
Hello @lindamacdonald . First of all, thank you for your feedback. We updated the preview links and fixed the problem. :)
You can view it https://contentrain-the-roads.netlify.app/
